# Generated by Django 2.2.24 on 2021-07-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuerda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serie_producto', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=50)),
                ('Codigo', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('Disponible', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
