# Generated by Django 2.2.24 on 2021-07-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuerda',
            name='tipo',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
    ]
