# Generated by Django 2.2.24 on 2021-07-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_cuerda_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serie_producto', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=50)),
                ('Codigo', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('Disponible', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Amplificador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serie_producto', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=50)),
                ('Codigo', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('Disponible', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Percusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serie_producto', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=50)),
                ('Codigo', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('Disponible', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
